export const SET_USER = 'SET_USER'

export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS'

export const SET_HISTORY_ACTIVE = 'SET_HISTORY_ACTIVE'

export const SET_TOP_MENU = 'SET_TOP_MENU'

export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'