export const SET_USER = 'SET_USER'

export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS'

export const SET_HISTORY_ACTIVE = 'SET_HISTORY_ACTIVE'

export const SET_TOP_MENU = 'SET_TOP_MENU'

export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
  
export const SAVE_LIST_PAGE_PARS = 'SAVE_LIST_PAGE_PARS'

export const REMOVE_LIST_PAGE_PARS = 'REMOVE_LIST_PAGE_PARS'

export const SET_EXPORT_BTN = 'SET_EXPORT_BTN'